#ifdef LANGUAGE_ENGLISH               // English language support (copy leading and trailing spaces when making your own language section)
#define MOON_STRING "moon "
#define SUN_STRING "sun "
#define AZ_TARGET_STRING "Az Target "
#define EL_TARGET_STRING "El Target "
#define TARGET_STRING "Target "
#define PARKING_STRING "Parking"
#define PARKED_STRING "Parked"
/*
#define ROTATING_CW_STRING "Rotating CW"    // depricated in 2015090402
#define ROTATING_CCW_STRING "Rotating CCW"
#define ROTATING_TO_STRING "Rotating to "
#define ELEVATING_TO_STRING "Elevating to "
#define ELEVATING_UP_STRING "Elevating Up"
#define ELEVATING_DOWN_STRING "Elevating Down"
#define ROTATING_STRING "Rotating "
*/
#define CW_STRING "CW"
#define CCW_STRING "CCW"
#define UP_STRING "UP"
#define DOWN_STRING "DOWN"
#define AZIMUTH_STRING "Azimuth "
#define AZ_STRING "Az"
#define AZ_SPACE_STRING "Az "
#define ELEVATION_STRING "Elevation "
#define SPACE_EL_STRING " El"
#define SPACE_EL_SPACE_STRING " El "
#define GPS_STRING "GPS"
#define N_STRING "N"
#define W_STRING "W"
#define S_STRING "S"
#define E_STRING "E"
#define NW_STRING "NW"
#define SW_STRING "SW"
#define SE_STRING "SE"
#define NE_STRING "NE"
#define NNW_STRING "NNW"
#define WNW_STRING "WNW"
#define WSW_STRING "WSW"
#define SSW_STRING "SSW"
#define SSE_STRING "SSE"
#define ESE_STRING "ESE"
#define ENE_STRING "ENE"
#define NNE_STRING "NNE"
#endif //LANGUAGE_ENGLISH

#ifdef LANGUAGE_SPANISH               // Courtesy of Maximo, EA1DDO
#define MOON_STRING "Luna "
#define SUN_STRING "Sol "
#define AZ_TARGET_STRING "Az Objetivo "
#define EL_TARGET_STRING "El Objetivo "
#define TARGET_STRING "Objetivo "
#define PARKING_STRING "Aparcando"
#define PARKED_STRING "Aparcado"
/*
#define ROTATING_CW_STRING "Girando Dcha"
#define ROTATING_CCW_STRING "Girando Izq"
#define ROTATING_TO_STRING "Girando a "
#define ELEVATING_TO_STRING "Elevando a "
#define ELEVATING_UP_STRING "Subiendo"
#define ELEVATING_DOWN_STRING "Bajando"
#define ROTATING_STRING "Girando "
*/
#define CW_STRING "Dcha"
#define CCW_STRING "Izq"
#define UP_STRING "Arriba"
#define DOWN_STRING "Abajo"
#define AZIMUTH_STRING "Azimuth "
#define AZ_STRING "Az"
#define AZ_SPACE_STRING "Az "
#define ELEVATION_STRING "Elevation "
#define SPACE_EL_STRING " El"
#define SPACE_EL_SPACE_STRING " El "
#define GPS_STRING "GPS"
#define N_STRING "N"
#define W_STRING "O"
#define S_STRING "S"
#define E_STRING "E"
#define NW_STRING "NO"
#define SW_STRING "SO"
#define SE_STRING "SE"
#define NE_STRING "NE"
#define NNW_STRING "NNO"
#define WNW_STRING "ONO"
#define WSW_STRING "OSO"
#define SSW_STRING "SSO"
#define SSE_STRING "SSE"
#define ESE_STRING "ESE"
#define ENE_STRING "ENE"
#define NNE_STRING "NNE"
#endif //LANGUAGE_SPANISH

#ifdef LANGUAGE_CZECH            // courtesy of Jan, OK2ZAW
#define MOON_STRING "mesic "
#define SUN_STRING "slunce "
#define AZ_TARGET_STRING "Az cíl "
#define EL_TARGET_STRING "El cíl "
#define TARGET_STRING "Cil "
#define PARKING_STRING "Parking"
#define PARKED_STRING "Parkovat"
/*
#define ROTATING_CW_STRING "Otacim CW"
#define ROTATING_CCW_STRING "Otacim CCW"
#define ROTATING_TO_STRING "Otacim na "
#define ELEVATING_TO_STRING "Elevovat na "
#define ELEVATING_UP_STRING "Elevovat nahoru"
#define ELEVATING_DOWN_STRING "Elevovat dolu"
#define ROTATING_STRING "Otacet "
*/
#define CW_STRING "CW"
#define CCW_STRING "CCW"
#define UP_STRING "Nahoru"
#define DOWN_STRING "Dolu"
#define AZIMUTH_STRING "Azimut "
#define AZ_STRING "Az"
#define AZ_SPACE_STRING "Az "
#define ELEVATION_STRING "Elevation "
#define SPACE_EL_STRING " El"
#define SPACE_EL_SPACE_STRING " El "
#define GPS_STRING "GPS"
#define N_STRING "smer   ^   KL"
#define W_STRING "smer   <   HK"
#define S_STRING "smer   v   ZS"
#define E_STRING "smer   >   VK"
#define NW_STRING "smer   <    W"
#define SW_STRING "smer   v  VP8"
#define SE_STRING "smer   >   HZ"
#define NE_STRING "smer   ^   JA"
#define NNW_STRING "smer   ^   VE"
#define WNW_STRING "smer   <   CO"
#define WSW_STRING "smer   <   PY"
#define SSW_STRING "smer   v  ZD9"
#define SSE_STRING "smer   v   5R"
#define ESE_STRING "smer   >   8Q"
#define ENE_STRING "smer   >   ZL"
#define NNE_STRING "smer   ^  UA0"
#endif //LANGUAGE_CZECH

#ifdef LANGUAGE_ITALIAN    // courtesy of Paolo, IT9IPQ           
#define MOON_STRING "luna"
#define SUN_STRING "sole "
#define AZ_TARGET_STRING "Punta Az  "
#define EL_TARGET_STRING "Punta El  "
#define TARGET_STRING "Punta  "
#define PARKING_STRING "Posando"
#define PARKED_STRING "Posato"
/*
#define ROTATING_CW_STRING "Ruota DX > "
#define ROTATING_CCW_STRING "Ruota SX <  "
#define ROTATING_TO_STRING "Ruota verso "
#define ELEVATING_TO_STRING "Alza verso   "
#define ELEVATING_UP_STRING "Alzo  Su    "
#define ELEVATING_DOWN_STRING "Abbasso  Giu'    "
#define ROTATING_STRING "Ruota    "
*/
#define CW_STRING "DX"
#define CCW_STRING "SX "
#define UP_STRING "SU"
#define DOWN_STRING "GIU'"
#define AZIMUTH_STRING "Azimuth "
#define AZ_STRING "Az"
#define AZ_SPACE_STRING "Az "
#define ELEVATION_STRING "Elevation "
#define SPACE_EL_STRING " El"
#define SPACE_EL_SPACE_STRING " El "
#define GPS_STRING "GPS"
#define N_STRING "N"
#define W_STRING "W"
#define S_STRING "S"
#define E_STRING "E"
#define NW_STRING "NW"
#define SW_STRING "SW"
#define SE_STRING "SE"
#define NE_STRING "NE"
#define NNW_STRING "NNW"
#define WNW_STRING "WNW"
#define WSW_STRING "WSW"
#define SSW_STRING "SSW"
#define SSE_STRING "SSE"
#define ESE_STRING "ESE"
#define ENE_STRING "ENE"
#define NNE_STRING "NNE"
#endif //LANGUAGE_ITALIAN

#ifdef LANGUAGE_PORTUGUESE_BRASIL // courtesy of Ismael, PY4PI
#define MOON_STRING "lua "
#define SUN_STRING "sol "
#define AZ_TARGET_STRING "Objetivo Az "
#define EL_TARGET_STRING "Objetivo El "
#define TARGET_STRING "Objetivo "
#define PARKING_STRING "Parking"
#define PARKED_STRING "Estacionado"
/*
#define ROTATING_CW_STRING "Rodando DIR"
#define ROTATING_CCW_STRING "Rodando ESQ"
#define ROTATING_TO_STRING "Rodando para "
#define ELEVATING_TO_STRING "Elevando para "
#define ELEVATING_UP_STRING "Subindo"
#define ELEVATING_DOWN_STRING "Descendo"
#define ROTATING_STRING "Rodando "
*/
#define CW_STRING "DIR"
#define CCW_STRING "ESQ"
#define UP_STRING "SOBE"
#define DOWN_STRING "DESCE"
#define AZIMUTH_STRING "Azimute "
#define AZ_STRING "Az"
#define AZ_SPACE_STRING "Az "
#define ELEVATION_STRING "Elevation "
#define SPACE_EL_STRING " El"
#define SPACE_EL_SPACE_STRING " El "
#define GPS_STRING "GPS"
#define N_STRING "N"
#define W_STRING "O"
#define S_STRING "S"
#define E_STRING "L"
#define NW_STRING "NO"
#define SW_STRING "SO"
#define SE_STRING "SL"
#define NE_STRING "NL"
#define NNW_STRING "NNO"
#define WNW_STRING "ONO"
#define WSW_STRING "OSO"
#define SSW_STRING "SSO"
#define SSE_STRING "SSL"
#define ESE_STRING "LSL"
#define ENE_STRING "LNL"
#define NNE_STRING "NNL"
#endif //LANGUAGE_PORTUGUESE_BRASIL


#ifdef LANGUAGE_GERMAN               // courtesy of Ronny DM2RM
#define MOON_STRING "MOND "
#define SUN_STRING "SONNE "
#define AZ_TARGET_STRING "Az Ziel "
#define EL_TARGET_STRING "El Ziel "
#define TARGET_STRING "Ziel "
#define PARKING_STRING "Parken"
#define PARKED_STRING "Geparkt"
/*
#define ROTATING_CW_STRING "Drehen CW"
#define ROTATING_CCW_STRING "Drehen CCW"
#define ROTATING_TO_STRING "Drehen nach "
#define ELEVATING_TO_STRING "Elevation nach "
#define ELEVATING_UP_STRING "Elevation Auf"
#define ELEVATING_DOWN_STRING "Elevation Ab"
#define ROTATING_STRING "Drehen "
*/
#define CW_STRING "CW"
#define CCW_STRING "CCW"
#define UP_STRING "AUF"
#define DOWN_STRING "AB"
#define AZIMUTH_STRING "Azimuth "
#define AZ_STRING "Az"
#define AZ_SPACE_STRING "Az "
#define ELEVATION_STRING "Elevation "
#define SPACE_EL_STRING " El"
#define SPACE_EL_SPACE_STRING " El "
#define GPS_STRING "GPS"
#define N_STRING "N  (KL)"
#define W_STRING "W  (HK)"
#define S_STRING "S  (ZS)"
#define E_STRING "O  (YB)"
#define NW_STRING "NW  (W8)"
#define SW_STRING "SW  (PY)"
#define SE_STRING "SO  (HZ)"
#define NE_STRING "NO  (JA"
#define NNW_STRING "NNW (VE)"
#define WNW_STRING "WNW (XE)"
#define WSW_STRING "WSW (OA)"
#define SSW_STRING "SSW  (ZD7)"
#define SSE_STRING "SSO (5R)"
#define ESE_STRING "OSO (8Q)"
#define ENE_STRING "ONO (ZL)"
#define NNE_STRING "NNO (UA0)"
#endif //LANGUAGE_GERMAN

#ifdef LANGUAGE_FRENCH  // contributed by Marc-Andre, VE2EVN
#define MOON_STRING "lune "
#define SUN_STRING "soleil "
#define AZ_TARGET_STRING "Az Cible "
#define EL_TARGET_STRING "Él Cible "
#define TARGET_STRING "Cible "
#define PARKING_STRING "Parcage"
#define PARKED_STRING "Garé"
#define UP_STRING "HAUSSE"
//#define UP_STRING "HAUT"
#define DOWN_STRING "BAISSE"
//#define DOWN_STRING "BAS"
#define CW_STRING "SH"
#define CCW_STRING "SAH"
#define AZIMUTH_STRING "Azimut "
#define AZ_STRING "Az"
#define AZ_SPACE_STRING "Az "
#define ELEVATION_STRING "Elevation "
#define SPACE_EL_STRING " Él"
#define SPACE_EL_SPACE_STRING " Él "
#define GPS_STRING "GPS"
#define N_STRING "N"
#define W_STRING "O"
#define S_STRING "S"
#define E_STRING "E"
#define NW_STRING "NO"
#define SW_STRING "SO"
#define SE_STRING "SE"
#define NE_STRING "NE"
#define NNW_STRING "NNO"
#define WNW_STRING "ONO"
#define WSW_STRING "OSO"
#define SSW_STRING "SSO"
#define SSE_STRING "SSE"
#define ESE_STRING "ESE"
#define ENE_STRING "ENE"
#define NNE_STRING "NNE"
#endif //LANGUAGE_FRENCH

#ifdef LANGUAGE_DUTCH               // Dutch language support courtesy of David, ON4BDS
#define MOON_STRING "maan "
#define SUN_STRING "zon "
#define AZ_TARGET_STRING "Az Doel "
#define EL_TARGET_STRING "El Doel "
#define TARGET_STRING "Doel "
#define PARKING_STRING "Parkeren"
#define PARKED_STRING "Geparkeerd"
/*
#define ROTATING_CW_STRING "Roteren CW"    // depricated in 2015090402
#define ROTATING_CCW_STRING "Roteren CCW"
#define ROTATING_TO_STRING "Roteren naar "
#define ELEVATING_TO_STRING "Eleveren naar "
#define ELEVATING_UP_STRING "Eleveren Omhoog""
#define ELEVATING_DOWN_STRING "Eleveren Omlaag"
#define ROTATING_STRING "Roteren "
*/
#define CW_STRING "CW"
#define CCW_STRING "CCW"
#define UP_STRING "OP"
#define DOWN_STRING "Neer"
#define AZIMUTH_STRING "Azimuth "
#define AZ_STRING "Az"
#define AZ_SPACE_STRING "Az "
#define ELEVATION_STRING "Elevation "
#define SPACE_EL_STRING " El"
#define SPACE_EL_SPACE_STRING " El "
#define GPS_STRING "GPS"
#define N_STRING "N"
#define W_STRING "W"
#define S_STRING "Z"
#define E_STRING "O"
#define NW_STRING "NW"
#define SW_STRING "ZW"
#define SE_STRING "ZO"
#define NE_STRING "NO"
#define NNW_STRING "NNW"
#define WNW_STRING "WNW"
#define WSW_STRING "WZW"
#define SSW_STRING "ZZW"
#define SSE_STRING "ZZO"
#define ESE_STRING "OZO"
#define ENE_STRING "ONO"
#define NNE_STRING "NNO"
#endif //LANGUAGE_DUTCH